services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
